"""empty message

Revision ID: 2068f6be11eb
Revises: 23472cee8569
Create Date: 2023-08-12 23:52:12.837985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2068f6be11eb'
down_revision = '23472cee8569'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
