"""empty message

Revision ID: 23472cee8569
Revises: eab823663b62
Create Date: 2023-08-11 16:11:25.956002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23472cee8569'
down_revision = 'eab823663b62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
