
version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORTS}:${POSTGRES_PORTS}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORTS}:${REDIS_PORTS}
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORTS}:${APP_PORTS}
    volumes:
      - ./app:/app

volumes:
  postgres_data:
  redis_data:
