version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: kindude
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pg
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis
    restart: always
    ports:
      - 6378:6379
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app

volumes:
  postgres_data:
  redis_data:
